---
name: Auto merge

on:
  pull_request:

permissions:
  contents: write
  checks: read
  pull-requests: write

jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-auto-merge.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
    with:
      tfcheck: 'complete / Check code format'
...
