---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'tf-checks-complete-example / Check code format'
...
