name: Auto merge

on:
  pull_request:

permissions:
  contents: write
  checks: read
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-auto-merge.yml@v2
    with:
      azure_cloud: true
      tfchecks_azure: '["tf-lint / tflint"]'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
